### ISSUE TITLE
As a user managing multiple MOLGENIS instances I want to be able to select a MOLGENIS instance on the command line

### ISSUE THREAD

**Issue by djvanenckevort** [molgenis/molgenis-tools-commander#60]
### How to Reproduce
Run mcdm on the command line

### Expected behavior
I can pass the URL to the MOLGENIS instance

### Observed behavior
There is no option to pass the URL to the MOLGENIS instance

**Comment by tommydeboer** [comment]
@djvanenckevort You can add and select hosts in the properties file (stored in your home folder under `.mcmd/mcmd.yaml`). Example:

```yaml
host:
  selected: https://other.example.molgenis.org/
  auth:
  - url: http://localhost:8080/
    username: admin
    password: admin
  - url: https://other.example.molgenis.org/
    username: admin
    password: example
```

A command for this is being implemented and is planned for version 1.1, which will look like this:

```
mcmd config add host
```

and 

```
mcmd config set host
```
